# Generated by Django 2.2.1 on 2019-09-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190904_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, default='Unknown', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(max_length=250),
        ),
    ]
